name: CI-Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Release in GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: >
        gh release create ${{ github.ref_name }}
        -t "Release ${{ github.ref_name }}"
        -F changelog/${{ github.ref_name }}.md
        --generate-notes
